# Generated by Django 3.2.4 on 2021-06-19 03:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Furniture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('furnitureName', models.CharField(max_length=255)),
                ('dateEntered', models.DateTimeField()),
                ('furniturePrice', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('furnitureDescription', models.TextField(null=True)),
            ],
            options={
                'db_table': 'furniture',
            },
        ),
        migrations.CreateModel(
            name='FurnitureType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeName', models.CharField(max_length=255)),
                ('typeDescription', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'furnituretypes',
                'db_table': 'furnituretype',
            },
        ),
        migrations.CreateModel(
            name='FurnitureDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detailName', models.CharField(max_length=255)),
                ('length', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('materials', models.TextField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='franz.furniture')),
            ],
            options={
                'db_table': 'details',
            },
        ),
        migrations.AddField(
            model_name='furniture',
            name='furnitureType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='franz.furnituretype'),
        ),
        migrations.AddField(
            model_name='furniture',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
